In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/processed/jobs_detailed.csv")

In [4]:
df.head()

,title,company,posted_date,closing_date,city,region,category,url
0,Accounts Executive,Avenierr Pharma (Pvt) Ltd,2026-06-26,2026-07-10T00:00:00+0530,Kalubowila,Western,Executive,https://www.topjobs.lk/employer/JobAdvertismen...
1,Proofreader,B.R. De Silva & Co,2026-06-26,2026-07-10T00:00:00+0530,Colombo 5,Western,Other,https://www.topjobs.lk/employer/JobAdvertismen...
2,Quality Manager - Offset Printing,Company Name Withheld,2026-06-26,2026-07-10T00:00:00+0530,Colombo 1,Western,Management,https://www.topjobs.lk/employer/JobAdvertismen...
3,Attorneys - At - Law,Elite Law,2026-06-26,2026-07-10T00:00:00+0530,Boralesgamuwa,Western,Other,https://www.topjobs.lk/employer/JobAdvertismen...
4,Outlet Supervisor,Roots Global (Pvt) Ltd,2026-06-26,2026-07-10T00:00:00+0530,Colombo 1,Western,Other,https://www.topjobs.lk/employer/JobAdvertismen...

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3439 entries, 0 to 3438
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         3439 non-null   str
 1   company       3439 non-null   str
 2   posted_date   3439 non-null   str
 3   closing_date  3439 non-null   str
 4   city          3404 non-null   str
 5   region        3404 non-null   str
 6   category      3439 non-null   str
 7   url           3439 non-null   str
dtypes: str(8)
memory usage: 215.1 KB

In [6]:
df.isnull().sum()

title            0
company          0
posted_date      0
closing_date     0
city            35
region          35
category         0
url              0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df = df.drop_duplicates()

In [9]:
df["title"] = df["title"].str.strip()
df["company"] = df["company"].str.strip()
df["city"] = df["city"].str.strip()
df["region"] = df["region"].str.strip()
df["category"] = df["category"].str.strip()

In [10]:
df["posted_date"] = pd.to_datetime(df["posted_date"])
df["closing_date"] = pd.to_datetime(df["closing_date"])

In [11]:
df.dtypes

title                                 str
company                               str
posted_date                datetime64[us]
closing_date    datetime64[us, UTC+05:30]
city                                  str
region                                str
category                              str
url                                   str
dtype: object

In [13]:
df["posted_date"] = pd.to_datetime(df["posted_date"])

df["closing_date"] = pd.to_datetime(df["closing_date"]).dt.tz_localize(None)

In [14]:
df["days_open"] = (
    df["closing_date"] - df["posted_date"]
).dt.days

In [15]:
df.head()

,title,company,posted_date,closing_date,city,region,category,url,days_open
0,Accounts Executive,Avenierr Pharma (Pvt) Ltd,2026-06-26,2026-07-10,Kalubowila,Western,Executive,https://www.topjobs.lk/employer/JobAdvertismen...,14
1,Proofreader,B.R. De Silva & Co,2026-06-26,2026-07-10,Colombo 5,Western,Other,https://www.topjobs.lk/employer/JobAdvertismen...,14
2,Quality Manager - Offset Printing,Company Name Withheld,2026-06-26,2026-07-10,Colombo 1,Western,Management,https://www.topjobs.lk/employer/JobAdvertismen...,14
3,Attorneys - At - Law,Elite Law,2026-06-26,2026-07-10,Boralesgamuwa,Western,Other,https://www.topjobs.lk/employer/JobAdvertismen...,14
4,Outlet Supervisor,Roots Global (Pvt) Ltd,2026-06-26,2026-07-10,Colombo 1,Western,Other,https://www.topjobs.lk/employer/JobAdvertismen...,14

In [16]:
df.to_csv("../data/cleaned/jobs_cleaned.csv", index=False)